<?php
$ini = parse_ini_file("../config.ini.php", true);
$admin = $ini['login']['admin'];
$def_path = $ini['login']['default'];
$subdirectories = $ini['filepaths']['subdirectories'];
$key = $ini['login']['key'];
echo $key . " is the key !! \n \n";
$secret = $ini['login']['secret'];

session_start();

$token = $_SESSION['access_token'];

echo "hello !!! \n \n";
echo "hello II \n \n";
$user = "allenhub";

//fileToUpload=@json_to_send_from_template.json
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$theStringCommand = "curl -sk -H \"Authorization: Bearer 39b0c3cc120389a7f5b3862ee5b9a95\" -X POST -F \"fileToUpload=@json_to_send_from_template.json\" 'https://agave.iplantc.org/jobs/v2/?pretty=true'";


//curl -sk -H "Authorization: Bearer 39b0c3cc120389a7f5b3862ee5b9a95" -X POST -F "fileToUpload=@json_to_send_fro_template.json" 'https://agave.iplantc.org/jobs/v2/?pretty=true'


echo $theStringCommand  . " is the string command !!! \n \n";

//exec("curl -sk -H \"Authorization: Bearer $token \" -X POST -F \"fileToUpload=@json_to_send_fro_template.json\" 'https://agave.iplantc.org/jobs/v2/?pretty=true' > info_here");
exec("$theStringCommand");

echo "after the submit !!";

?>
