
<?php
$ini = parse_ini_file("../config.ini.php", true);
$admin = $ini['login']['admin'];
$def_path = $ini['login']['default'];
$subdirectories = $ini['filepaths']['subdirectories'];
$key = $ini['login']['key'];
echo $key . " is the key !! \n \n";
$secret = $ini['login']['secret'];

session_start();

$token = $_SESSION['access_token'];

//curl -sk -H "Authorization: Bearer 435152f948cfd44274552c95695126c" -X PUT -d "action=move&path=ex3.fastq" 'https://agave.iplantc.org/files/v2/media/allenhub/ex1.fastq?pretty=true'


//allenhub/Transcriptome_Delaware$file

//the array of the files:
$files = array("744_16_CCGTCC_L002_R1_001.fastq.gz", "744_16_CCGTCC_L002_R2_001.fastq.gz");    
$destPath = "allenhub";
$fqFileDir = "allenhub/Transcriptome_Delaware";

foreach($files as $file)
{

    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, "https://agave.iplantc.org/files/v2/media/$fqFileDir/$file?pretty=true");
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, "action=move&path=$destPath/$file");
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "PUT");


    $headers = array();
    $headers[] = "Authorization: Bearer $token";
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close ($ch);
	echo $result;
	echo "is the result !! \n \n";
}

echo "we did the command just now !! \n \n";

?>
