<?php
$ini = parse_ini_file("../config.ini.php", true);
$def_path = $ini['login']['default'];
$subdirectories = $ini['filepaths']['subdirectories'];
#echo $subdirectories . "is subdirectories !!!";
#echo "hello this message is working !!";
$key = $ini['login']['key'];
$secret = $ini['login']['secret'];

session_start();

$token = $_SESSION['access_token'];
$time_out = $_SESSION['SESSION_TIMEOUT'];
$user = $_SESSION['user_name'];





// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, "https://agave.iplantc.org/files/v2/pems/allenhub/allenhubCogeTestII?pretty=true");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "username=coge&permission=WRITE&recursive=false");
curl_setopt($ch, CURLOPT_POST, 1);

$headers = array();
$headers[] = "Authorization: Bearer $token";
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close ($ch);
echo $result . " is the result !!";

echo $token . " is the token !!! \n \n";

$authorization = "Authorization: Bearer $token";

$ch = curl_init("https://agave.iplantc.org:443/files/v2/listings/$user/fqfiles");

//echo "made the change !! \n \n";
curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: application/json' , $authorization ));
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
$result = curl_exec($ch);
//echo "$result is the result !!! \n";

curl_close($ch);
$theDictionary = json_decode($result);
echo $result . "is result II";

?>
