
<?php
$ini = parse_ini_file("../config.ini.php", true);
$admin = $ini['login']['admin'];
$def_path = $ini['login']['default'];
$subdirectories = $ini['filepaths']['subdirectories'];
$key = $ini['login']['key'];
echo $key . " is the key !! \n \n";
$secret = $ini['login']['secret'];

session_start();

$token = $_SESSION['access_token'];

//curl -sk -H "Authorization: Bearer 435152f948cfd44274552c95695126c" -X PUT -d "action=move&path=ex3.fastq" 'https://agave.iplantc.org/files/v2/media/allenhub/ex1.fastq?pretty=true'


//allenhub/Transcriptome_Delaware$file

//the array of the files:
//$files = array("744_16_CCGTCC_L002_R1_001.fastq.gz", "744_16_CCGTCC_L002_R2_001.fastq.gz");    
$files = array("allen_man1.txt", "allen_man2.txt");

$destPath = "allenhub";
$fqFileDir = "allenhub/Transcriptome_Delaware";



//upload the manifest into the user's temp directory




//foreach($files as $file)
//{

	//exec("curl -# -k -H \"Authorization: Bearer $token \" -X POST -F "fileToUpload=@allen_system_register_command_roger_agave_III.json" -F "fileName=allen_uploadJSON" 'https://agave.iplantc.org/files/v2/media/allenhub?pretty=true');
//        exec(" bash files-upload -F allen_to_upload.txt -N allen_uploadJSONII  allenhub");

	//upload the manifest into the user's temp directory
	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
//	$ch = curl_init();

	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
//	$ch = curl_init();

//	curl_setopt($ch, CURLOPT_URL, "https://agave.iplantc.org/files/v2/media/allenhub?pretty=true");
//	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
//	curl_setopt($ch, CURLOPT_POST, 1);

//	$headers = array();
//	$headers[] = "Authorization: Bearer $token";
//	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

//	$result = curl_exec($ch);
//	if (curl_errno($ch)) {
  //  		echo 'Error:' . curl_error($ch);
//	}
//	curl_close ($ch);

//	echo $ch . " is the result of ch for the upload !!!"




    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
/*

    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, "https://agave.iplantc.org/files/v2/media/$fqFileDir/$file?pretty=true");
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, "action=move&path=$destPath/$file");
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "PUT");


    $headers = array();
    $headers[] = "Authorization: Bearer $token";
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close ($ch);
*/

//	echo $result;
//	echo "is the result !! \n \n";
//}


//exec(" bash new_agave/foundation-cli/bin/files-upload -z $token -F allen_to_upload.txt -N allen_uploadJSONII  allenhub");

//exec("bash /opt/apache2/frankdec_dev/new_agave/foundation-cli/bin/files-upload -z $token -F allen_to_upload.txt -N allen_uploadJSONII  allenhub");
/*

        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
      $ch = curl_init();

      curl_setopt($ch, CURLOPT_URL, "https://agave.iplantc.org/files/v2/media/allenhub?pretty=true");
      curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
      curl_setopt($ch, CURLOPT_POST, 1);

      $headers = array();
      $headers[] = "Authorization: Bearer $token";
      curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

      $result = curl_exec($ch);
      if (curl_errno($ch)) {
              echo 'Error:' . curl_error($ch);
      }
      curl_close ($ch);

//      echo $ch . " is the result of ch for the upload !!!"
*/

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
/*

$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, "https://agave.iplantc.org/files/v2/media/allenhub?pretty=true");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "fileToUpload=@allen_to_upload.txt");
curl_setopt($ch, CURLOPT_POST, 1);

$headers = array();
$headers[] = "Authorization: Bearer $token";
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close ($ch);

echo $result;
echo " is the result from ch !!!";

echo "we did the command just now2 !! \n \n";
*/

function httpPost($url,$params)
{
  $postData = '';
   //create name value pairs seperated by &
   foreach($params as $k => $v) 
   { 
      $postData .= $k . '='.$v.'&'; 
   }
   $postData = rtrim($postData, '&');
 
    $ch = curl_init();  
 
    curl_setopt($ch,CURLOPT_URL,$url);
    curl_setopt($ch,CURLOPT_RETURNTRANSFER,true);
    curl_setopt($ch,CURLOPT_HEADER, false); 
    curl_setopt($ch, CURLOPT_POST, count($postData));
        curl_setopt($ch, CURLOPT_POSTFIELDS, $postData);    
 
    $output=curl_exec($ch);
 
    curl_close($ch);
    return $output;
 
}

/*
$params = array(
   "name" => "Ravishanker Kusuma",
   "age" => "32",
   "location" => "India"
);

$params  = array(
  "fileType" => "string",
  "fileName "=> "string",
  "append" => false
}



echo httpPost("https://agave.iplantc.org/files/v2/media/allenhub?pretty=true",$params);
*/


?>
